# Generated by Django 3.2.18 on 2023-05-07 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booked_on',
        ),
    ]
